# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.1
neo_version=21.1.206
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.forcecraft
mod_id=forcecraft
mod_archive_name=forcecraft

# Version
version=6.2.5

#Publishing
mod_name=Forcecraft
curseforge_id=454802
modrinth_id=Nwz7U1QT

# Dependencies
jei_minecraft=1.21.1
jei_version=19.22.1.316
rei_version=16.0.799
architectury_version=13.0.8
cloth_config_version=15.0.140
patchouli_version=1.21.1-92-NEOFORGE
patchouli_provider_version=1.21.1-1.0.11-Snapshot.5
