# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.1
neo_version=21.1.93
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.forcecraft
mod_id=forcecraft
mod_archive_name=forcecraft

# Version
version=6.1.1

#Publishing
mod_name=Forcecraft
curseforge_id=454802
modrinth_id=Nwz7U1QT

# Dependencies
jei_minecraft=1.21.1
jei_version=19.21.0.247
patchouli_version=1.21-87-NEOFORGE
patchouli_provider_version=1.21.1-1.0.11-Snapshot.3
