modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/mrbysco/forcecraft/issues"
license="GNU GPL v3"

[[mods]]
modId="forcecraft"
version="${file.jarVersion}"
displayName="ForceCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/forcecraft"
authors="Mrbysco"
credits="Bluedart for the Original Mod"
description='''
A mod inspired by DartCraft
'''
[[dependencies.forcecraft]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
[[dependencies.forcecraft]]
modId="forge"
mandatory=true
versionRange="[36.2.17,)"
ordering="NONE"
side="BOTH"